#!/usr/bin/env bash

# Prowler - the handy cloud security tool (copyright 2018) by Toni de la Fuente
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

GROUP_ID[99]='smb'
GROUP_NUMBER[99]='99.0'
GROUP_TITLE[99]='Security Check - [smb] Security Assessment for SMB'
GROUP_CHECKS[99]='check112,check113,check119,check12,extra71,extra7123,extra7141,extra741,extra742,extra759,extra760,extra768,extra775,check11,check122,extra7100,extra7185,check41,check42,extra711,extra7134,extra7135,extra7136,extra7137,extra7140,extra7143,extra7145,extra7147,extra716,extra7177,extra7178,extra7179,extra7186,extra72,extra723,extra727,extra73,extra731,extra736,extra749,extra750,extra751,extra752,extra753,extra754,extra755,extra76,extra77,extra771,extra779,extra78,extra787,extra788,extra795,extra796,extra798,check43,check21,check22,check23,check118,check25,extra713,extra7139,extra730,extra769,extra799,extra729,extra735,extra740,extra761,extra797'